Eventor_Project/Eventor_Project/Controllers/AlbumController.cs
using Eventor_Project.Auth;
using Eventor_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eventor_Project.Models.User;
using System.IO;
namespace Eventor_Project.Controllers
{
    public class AlbumController : BaseController
    {
        private readonly CurrentContext db = new CurrentContext();

        //
        // GET: /Album/
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Pictures.Where(x => x.OwnerId == CurrentUser.UserId));
        }

        //
        // GET: /Album/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Album/LoadPicture
        [Authorize]
        [HttpPost]
        public ActionResult LoadPicture(Picture pic, HttpPostedFileBase uploadImage)
        {
            if (uploadImage != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                // установка массива байтов
                pic.OwnerId = CurrentUser.UserId;
                pic.Image = imageData;

                Repository.CreatePicture(pic);

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        //
        // POST: /Album/NewPicture

        public ActionResult NewPicture()
        {
            return View();
        }

        //
        // GET: /Album/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Album/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Album/Delete/5

        public ActionResult Delete(int id)
        {
            Repository.DeletePicture(id);
            return RedirectToAction("Index");
        }

        //
        // POST: /Album/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Eventor_Project/Eventor_Project/Controllers/ProjectsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Eventor_Project.Models.ProjectModel;
using Newtonsoft.Json;
using Ninject.Infrastructure.Language;
using Eventor_Project.Models.ViewModels;
using Eventor_Project.Models.ProjectModel.Relations;

namespace Eventor_Project.Controllers
{
    public class ProjectsController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            var projectsViewModel = Repository.Projects.ToList()
                .Select(m=>(ProjectCardViewModel)ModelMapper.Map(m, typeof(Project), typeof(ProjectCardViewModel))).ToList();
            ViewBag.Categories = Repository.Categories.ToList();
            return View(projectsViewModel);
        }

        [HttpPost]
        public ActionResult Index(IEnumerable<Project> projects)
        {
            projects = projects ?? Repository.Projects;
            var projectsViewModel = projects.ToList()
                .Select(m => (ProjectCardViewModel)ModelMapper.Map(m, typeof(Project), typeof(ProjectCardViewModel))).ToList();
            ViewBag.Categories = Repository.Categories.ToList();
            return View(projectsViewModel);
        }

        [HttpGet]
        public ActionResult Project(int projectId)
        {
            var project = Repository.ReadProject(projectId);
            if (project == null)
            {
                return HttpNotFound();
            }
            var projectView = (ProjectCardViewModel)ModelMapper.Map(project, typeof(Project), typeof(ProjectCardViewModel));
            var customList = new SelectList(Repository.Customers.Where(m => m.ProjectId == projectId), "customerId", "Role");
            ViewBag.customerId =customList;
            ViewBag.organizerId = new SelectList(Repository.Organisers.Where(m => m.ProjectId == projectId), "organizerId", "Name");
            return View(projectView);
        }

        [HttpPost,Authorize]
        public ActionResult Project(int projectId, int? customerId, int? organizerId)
        {
            var project = Repository.ReadProject(projectId);
            if (customerId != null && customerId != 0)
            {
                var customer = project.Customers.First(m => m.CustomerId == customerId);
                var customers = customer.Customers;
                if (!customers.Contains(CurrentUser))
                {
                    customers.Add(CurrentUser);
                }

                Repository.UpdateCustomer(customer);
            }
            if (organizerId != null)
            {
                var organiser = project.Organisers.First(m => m.OrganizerId == organizerId);
                var organisers = organiser.Users;
                if (!organisers.Contains(CurrentUser))
                {
                    organisers.Add(CurrentUser);
                }
                Repository.UpdateOrganizer(organiser);
            }
            ViewBag.customerId = new SelectList(Repository.Customers.Where(m => m.ProjectId == projectId), "customerId", "Role");
            ViewBag.organizerId = new SelectList(Repository.Organisers.Where(m => m.ProjectId == projectId), "organizerId", "Name");
            var projectView = (ProjectCardViewModel)ModelMapper.Map(project, typeof(Project), typeof(ProjectCardViewModel));
            return View(projectView);
        }

        [HttpGet, Authorize]
        public ActionResult Add()
        {
            var project = new  Project()
            {
                AuthorId = CurrentUser.UserId,
                EventDate = null,
                OrganizationDate = null,
                AddedTime = DateTime.Now,
                ChangeTime = DateTime.Now
            };
            var result = Repository.CreateProject(project);
            return RedirectToAction("Edit", new {projectId=project.ProjectId});
        }

        [HttpGet,Authorize]
        public ActionResult Delete(int projectId)
        {
            var result = Repository.DeleteProject(projectId);
            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpGet,Authorize]
        public ActionResult Edit(int projectId)
        {
            var project = Repository.ReadProject(projectId);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(Repository.Categories, "CategoryId", "Name", project.CategoryId);
            return View(project);
        }

        [HttpPost,Authorize]
        public ActionResult Edit(Project project)
        {

            ViewBag.CategoryId = new SelectList(Repository.Categories, "CategoryId", "Name", project.CategoryId);
            if (ModelState.IsValid)
            {
                var result = Repository.UpdateProject(project);
            }
            return RedirectToAction("Edit", new { projectId = project.ProjectId });
        }

        #region Inventory_Methods

        [HttpGet, Authorize]
        public JsonResult GetMaterials(int projectId)
        {
            var materials = Repository.ReadProject(projectId)
                .Inventory.Select(m => ModelMapper.Map(m, typeof(Material), typeof(MaterialsJsonModel))).ToEnumerable();
            if (materials == null)
                return Json("");
            return Json(materials, JsonRequestBehavior.AllowGet);
        }
        [HttpPost, Authorize]
        public JsonResult SaveMaterials(List<Material> materials)
        {
            Repository.SaveMaterials(materials);
            return Json("");
        }

        [HttpPost, Authorize]
        public JsonResult SaveMaterialsUser(List<UserMaterial> userMaterials)
        {
            if (userMaterials != null)
            {
                foreach (var item in userMaterials)
                {
                    item.UserId = CurrentUser.UserId;
                    Repository.CreateUserMaterial(item);
                }
            }
            return Json("");
        }
        #endregion
        #region Customers Methods
        [HttpGet, Authorize]
        public JsonResult GetCustomers(int projectId)
        {
            var customers = Repository.ReadProject(projectId)
                .Customers.Select(c => ModelMapper.Map(c, typeof(Customer), typeof(CustomerJsonModel))).ToEnumerable();
            if (customers == null)
                return Json("");
            return Json(customers, JsonRequestBehavior.AllowGet);
        }
        [HttpPost,Authorize]
        public JsonResult SaveCustomers(List<Customer> customers)
        {
            Repository.SaveCustomers(customers);
            return Json("");
        }
        #endregion
        #region Organizers Methods
        [HttpGet, Authorize]
        public JsonResult GetOrganizers(int projectId)
        {
            var organisers = Repository.ReadProject(projectId)
                .Organisers.Select(o => ModelMapper.Map(o, typeof(Organizer), typeof(OrganizerJsonModel))).ToEnumerable();
            if (organisers == null)
                return Json("");
            return Json(organisers, JsonRequestBehavior.AllowGet);
        }

        [HttpPost,Authorize]
        public JsonResult SaveOrganisers(List<Organizer> organisers)
        {
            Repository.SaveOrganisers(organisers);
            return Json("");
        }

        #endregion

        [Authorize]
        public ActionResult MyProjects()
        {
            Func<Project, bool> filter = 
                p => 
                    p.AuthorId == CurrentUser.UserId ||
                    p.Organisers.Any(o => o.Users.Any(u => u.UserId == CurrentUser.UserId)) ||
                    p.Customers.Any(c => c.Customers.Any(u => u.UserId == CurrentUser.UserId));

            return View("Index", CardsByFilter(filter));
        }


        private IEnumerable<ProjectCardViewModel> CardsByFilter(Func<Project, bool> filer)
        {
            ViewBag.Categories = Repository.Categories.ToList();
            return Repository
                .Projects
                .ToList()
                .Where(filer)
                .Select(m => (ProjectCardViewModel) ModelMapper.Map(m, typeof (Project), typeof (ProjectCardViewModel)));
        }

        [HttpGet]
        public ActionResult Search(string title,  int? categoryId)
        {
            Func<Project, bool> titleFilter;
            Func<Project, bool> categoryFilter;

            if (String.IsNullOrEmpty(title))
                titleFilter = p => true;
            else
                titleFilter = p => !String.IsNullOrEmpty(p.Title) && p.Title.ToLower().Contains(title.ToLower());


            if (categoryId == 0 || categoryId == null)
                categoryFilter = p => true;
            else
                categoryFilter = p => p.CategoryId == categoryId;


            Func<Project, bool> searchFilter = p => titleFilter(p) && categoryFilter(p);

            return View("Index", CardsByFilter(searchFilter));
        }

        [HttpGet]

        public ActionResult CardsByCategory(int categoryId)
        {

            Func<Project, bool> categoryFilter = p => p.CategoryId == categoryId;
            return View("Index", CardsByFilter(categoryFilter));
        }
    }
}

Eventor_Project/Eventor_Project/Views/Shared/NotAdminPage.cshtml
@model IList<Eventor_Project.Models.User.Role>
@{
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eventor!</h2>

<h1>Недостаточно прав для данной операции</h1>

Eventor_Project/Eventor_Project/Views/Shared/NotFoundPage.cshtml
@model IList<Eventor_Project.Models.User.Role>
@{
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eventor!</h2>

<h1>Страница не найдена</h1>

Eventor_Project/Eventor_Project/Views/Shared/_Layout.cshtml
@using System.Globalization
@using Eventor_Project.Auth
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    <style>
        </style>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")*@
    <link href="/Content/bootstrap-datepicker3.css" rel="stylesheet" />
    <link href="/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="/Content/bootstrap-theme.css.map" rel="stylesheet" />
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/bootstrap.css.map" rel="stylesheet" />
    <link href="/Content/Site.css" rel="stylesheet" />

    <script src="/Scripts/jquery-2.1.4.js"></script>

    <script src="/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/"><i class="glyphicon glyphicon-picture"></i> Logo</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Проекты", "Index","Projects")</li>
                        <li>@Html.ActionLink("Пользователи", "Index","User")</li>
                    </ul>
                    <!--TODO: Search Form-->
                    <form  action=@Url.Action("Search", "Projects") class="navbar-form navbar-left center-block" role="search">
                        <div class="input-group">
                            <input type="text" name="title" value="" placeholder="Поиск проекта" class="form-control" />
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </span>
                        </div>
                    </form>
                        <ul class=" nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Создать", "Add", "Projects")</li>
                            @if (ViewBag.CurrentUser == null)
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false">

                                        <i class="glyphicon glyphicon-log-in"></i> <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Вход", "Index", "Login")</li>
                                        <li>@Html.ActionLink("Регистрация", "Index", "Register")</li>
                                    </ul>
                                </li>
                            }
                            else
                            {
                                
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false">

                                        @ViewBag.CurrentUser.Name <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <!--Insert your links here-->
                                        <li>@Html.ActionLink("Страница пользователя", "Details", "User")</li>
                                        <li>@Html.ActionLink("Сообщения", "Index", "Mail")</li>
                                        <li>@Html.ActionLink("Мои проекты", "MyProjects", "Projects")</li>
                                        <li>@Html.ActionLink("Фотоальбом", "Index", "Album")</li>
                                        <li role="separator" class="divider"></li>
                                        <li>@Html.ActionLink("Настройки", "Edit", "User")</li>
                                        <li>@Html.ActionLink("Выход", "Logout", "Login")</li>
                                    </ul>
                                </li>
                            }
                        </ul>
                </div>
            </div>
    </nav>
<main>
    @RenderBody()
</main>    
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/main")
    @RenderSection("scripts", false)
</body>
</html>