Eventor_Project/Eventor_Project/Models/SqlRepository/User.cs
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eventor_Project.Models.SqlRepository
{
    public partial class SqlRepository
    {



        public IQueryable<User.User> Users
        {
            get
            {
                return Db.Users;
            }
        }

        public bool CreateUser(User.User instance)
        {
            if (instance.UserId == 0)
            {
                Db.Users.Add(instance);
                Db.SaveChanges();
                return true;
            }

            return false;
        }

        public bool UpdateUser(User.User instance)
        {
            User.User cache = Db.Users.Where(p => p.UserId == instance.UserId).FirstOrDefault();
            if (cache != null)
            {
                //cache.ContactEmail = instance.ContactEmail;
                //cache.Email = instance.Email;
                //cache.Name = instance.Name;
                //cache.Nickname = instance.Nickname;
                //cache.Patronymic = instance.Patronymic;
                //cache.PhoneNumber = instance.PhoneNumber;
                //cache.PlaceOfLiving = instance.PlaceOfLiving;
                //cache.PlaceOfStudy = instance.PlaceOfStudy;
                //cache.Sex = instance.Sex;
                //cache.Surname = instance.Surname;

                //cache.Benefits = instance.Benefits;
                //cache.Roles = instance.Roles;

                cache = instance;
                Db.SaveChanges();
                return true;
            }

            return false;
        }

        public bool DeleteUser(int UserId)
        {
            User.User instance = Db.Users.Where(p => p.UserId == UserId).FirstOrDefault();
            if (instance != null)
            {
                Db.Users.Remove(instance);
                Db.SaveChanges();
                return true;
            }

            return false;
        }

        public User.User ReadUser(int UserId)
        {
            User.User instance = Db.Users.Where(p => p.UserId == UserId).FirstOrDefault();
            return instance;
        }
        
    }
}

Eventor_Project/Eventor_Project/Models/User/Benefit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Eventor_Project.Models.User
{
    public class Benefit
    {
        [Key]
        public int BenefitId { get; set; }
        [MaxLength(50), Required]
        public string Code { get; set; }
        [MaxLength(50)]
        public string Name { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}

Eventor_Project/Eventor_Project/Models/User/Contacts.cs
namespace Eventor_Project.Models
{
    public class Contacts
    {
        public int ContactsId { get; set; }
        public string ContactEmail { get; set; }
        public string PhoneNumber { get; set; }


        public int UserId { get; set; }
        public virtual User User { get; set; }
    }
}

Eventor_Project/Eventor_Project/Models/User/Message.cs
using System.Collections.Generic;
using Eventor_Project.Models.ProjectModel;
using Eventor_Project.Models.ProjectModel.Relations;
using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using Eventor_Project.Models.SqlRepository;
using Ninject;

namespace Eventor_Project.Models.User
{
    public class Message
    {
        [Key]
        public int MessageId { get; set; }

        [Required]
        public int ReceiverId { get; set; }

        [Required]
        public int SenderId { get; set; }

        public int? PrevMessageId { get; set; }

        [Required]
        public string ReceiverNick { get; set; }

        [Required]
        public string SenderNick { get; set; }

        [Required, MaxLength(100)]
        public string Topic { get; set; }

        [Required, MaxLength(5000)]
        public string Text { get; set; }

        [DisplayName("Время отправления")]
        public DateTime DepartureTime { get; set; }

    }
}

Eventor_Project/Eventor_Project/Models/User/Place.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Eventor_Project.Models.User
{
    public class Place
    {
        [Key]
        public int PlaceId { get; set; }
        [MaxLength(2000)]
        public string PlaceInfo { get; set; }

        [InverseProperty("PlaceOfLiving")]
        public virtual ICollection<User> LivingUsers { get; set; }

        [InverseProperty("PlaceOfStudy")]
        public virtual ICollection<User> StudyingUsers { get; set; }

    }
}

Eventor_Project/Eventor_Project/Models/User/Role.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Eventor_Project.Models.User
{
    public class Role
    {
        [Key]
        public int RoleId { get; set; }
        [MaxLength(50), Required]
        public string Code { get; set; }
        [MaxLength(50)]
        public string Name { get; set; }
        public virtual ICollection<User> Users { get; set; }
   }
}

Eventor_Project/Eventor_Project/Models/User/Sex.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eventor_Project.Models.User
{
    public enum Sex
    {
        Male = 0,
        Female = 1
    };
}

Eventor_Project/Eventor_Project/Controllers/User/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eventor_Project.Controllers.User
{
    public class LoginController : Controllers.BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new Models.ViewModels.LoginView());
        }

        [HttpPost]
        public ActionResult Index(Models.ViewModels.LoginView loginView)
        {
            if (ModelState.IsValid)
            {
                var user = Auth.Login(loginView.Email, loginView.Password, loginView.IsPersistent);
                if (user != null)
                {
                    return RedirectToAction("Index", "Projects");
                }
                ModelState["Password"].Errors.Add("Неверный логин или пароль!");
            }
            return View(loginView);
        }

        public ActionResult Logout()
        {
            Auth.LogOut();
            return RedirectToAction("Index", "Projects");
        }
    }

}

Eventor_Project/Eventor_Project/Controllers/User/MailController.cs
using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Eventor_Project.Models;
using Eventor_Project.Models.ViewModels;
using Eventor_Project.Models.User;
namespace Eventor_Project.Controllers.User
{
    public class MailController : BaseController
    {
        private readonly CurrentContext db = new CurrentContext();
        //
        // GET: /Mail/

        [Authorize]
        public ActionResult Index()
        {
            return View(db.Messages.Where(x => x.SenderId == CurrentUser.UserId || x.ReceiverId == CurrentUser.UserId));
        }

        [Authorize]
        [HttpPost]
        public ActionResult NewMessage(int recId = -1, int prevMessageId = -1)
        {
            var message = new MessageView();
            message.ReceiverId = recId;
            message.ReceiverNick = Repository.GetUser(recId).Nickname;
            message.SenderId = CurrentUser.UserId;
            message.SenderNick = CurrentUser.Nickname;
            message.PrevMessage = ((prevMessageId > 0) ? Repository.ReadMessage(prevMessageId) : null);
            message.Topic = ((message.PrevMessage != null) ? "Re: " + message.PrevMessage.Topic : null);
            return View(message);
        }

        [Authorize]
        [HttpPost]
        public ActionResult SendMessage(MessageView messageView)
        {
            if (ModelState.IsValid)
            {
                var message = (Message)ModelMapper.Map(messageView, typeof(MessageView), typeof(Message));
                Repository.CreateMessage(message);
                return RedirectToAction("Index");
            }
            return View("NewMessage", messageView);
        }

    }
}

Eventor_Project/Eventor_Project/Controllers/User/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eventor_Project.Models;
using Eventor_Project.Models.ViewModels;
using Eventor_Project.Tools;
using System.Drawing.Imaging;
using System.Reflection;
using Ninject;
using Eventor_Project.Auth;


namespace Eventor_Project.Controllers.User 
{
    public class RegisterController : BaseController
    {

        [HttpGet]
        public ActionResult Index()
        {
            var newUserView = new UserRegisterView();
            return View(newUserView);
        }

        [HttpPost]
        public ActionResult Index(UserRegisterView userView)
        {
            var anyUser = Repository.Users.Any(p => string.Compare(p.Email, userView.Email) == 0);
            if (anyUser)
            {
                ModelState.AddModelError("Email", "Пользователь с таким email уже зарегистрирован");
            }
            if (ModelState.IsValid)
            {
                var user = (Models.User.User)ModelMapper.Map(userView, typeof(UserRegisterView), typeof(Models.User.User));
                Repository.CreateUser(user);
                return RedirectToAction("Index", "Login");
            }
            return View(userView);
        }
    }
}

Eventor_Project/Eventor_Project/Controllers/User/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eventor_Project.Models;
using Eventor_Project.Models.ViewModels;
using Eventor_Project.Tools;
using System.Drawing.Imaging;
using System.Reflection;
using Ninject;
using Eventor_Project.Auth;

namespace Eventor_Project.Controllers.User
{
    public class UserController : BaseController
    {
        private readonly CurrentContext db = new CurrentContext();

        public ActionResult Captcha()
        {
            Session[CaptchaImage.CaptchaValueKey] = new Random(DateTime.Now.Millisecond).Next(1111, 9999).ToString();
            var ci = new CaptchaImage(Session[CaptchaImage.CaptchaValueKey].ToString(), 211, 50, "Arial");

            // Change the response headers to output a JPEG image.
            this.Response.Clear();
            this.Response.ContentType = "image/jpeg";

            // Write the image to the response stream in JPEG format.
            ci.Image.Save(this.Response.OutputStream, ImageFormat.Jpeg);

            // Dispose of the CAPTCHA image object.
            ci.Dispose();
            return null;
        }

        //
        // GET: /User/

        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        [Authorize]
        public ActionResult AIndex()
        {

            if (CurrentUser.InRoles("admin"))
            {
                //Разрешен просмотр панели управления
                return View(db.Users.ToList());
            }
            return RedirectToNotAdminPage;
            
        }
        //
        // GET: /User/


        [Authorize] 
        public ActionResult Details()
        {
            return View("Info", CurrentUser);
        }

        public ActionResult Info(int id = 0)
        {
            return View(Repository.GetUser(id) ?? CurrentUser);
        }


        [Authorize]
        public ActionResult Edit()
        {
            return View("Edit", CurrentUser);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.User.User user)
        {
            if (ModelState.IsValid)
            {
                Repository.UpdateUser(user);
                return RedirectToAction("Details");
            }
            return View(user);
        }

        //
        // GET: /User/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {

            Models.User.User user = Repository.GetUser(id);
            if (user != null)
            {
                if (CurrentUser.InRoles("admin"))
                {
                    //Разрешено удаление
                    return View(user);
                }
                return RedirectToNotAdminPage;
            }
            return RedirectToNotFoundPage;
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (CurrentUser.InRoles("admin"))
            {
                Repository.DeleteUser(id);
                return RedirectToAction("Index");
            }
            return RedirectToNotAdminPage;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        private IEnumerable<Models.User.User> UsersByFilter(Func<Models.User.User, bool> filer)
        {
            var fios = Repository.Users.ToList().Select(u => u.Fio2.ToLower()).ToList();
            return Repository
                .Users
                .ToList()
                .Where(filer);
        }

        [HttpGet]
        public ActionResult Search(string title)
        {
            title = title ?? "";
            title = title.ToLower();
            Func<Models.User.User, bool> filter = p => p.Nickname.ToLower().Contains(title) || p.Fio2.ToLower().Contains(title);
            return View("Index", UsersByFilter(filter));
        }
    }
}

Eventor_Project/Eventor_Project/Views/User/AIndex.cshtml
@model IEnumerable<Eventor_Project.Models.User.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <p>
        @Html.ActionLink("Register New", "Register")
    </p>

    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nickname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patronymic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nickname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Patronymic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
                    @Html.ActionLink("Info", "Info", new { id = item.UserId })
                    @Html.ActionLink("Delete", "Delete", new { id = item.UserId })

                </td>
            </tr>
        }

    </table>
</div>

Eventor_Project/Eventor_Project/Views/User/Delete.cshtml
@model Eventor_Project.Models.User.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <fieldset>
        <legend>
            @Html.DisplayFor(model => model.Nickname)
        </legend>
    </fieldset>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" value="Delete" /> |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }
</div>

Eventor_Project/Eventor_Project/Views/User/Details.cshtml
@model Eventor_Project.Models.User.User
@{
    ViewBag.Title = "Личный кабинет";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Мой профиль (id: @Model.UserId)</h2>
    <fieldset>
        <legend>
            @String.Format(Model.Surname + " " + Model.Name)
        </legend>

        <div class="display-label">
            @Html.LabelFor(model => model.Email)<b>:</b>
            @Html.DisplayFor(model => model.Email)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Sex)<b>:</b>
            @Html.DisplayFor(model => model.Sex)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Nickname)<b>:</b>
            @Html.DisplayFor(model => model.Nickname)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Name)<b>:</b>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Surname)<b>:</b>
            @Html.DisplayFor(model => model.Surname)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Patronymic)<b>:</b>
            @Html.DisplayFor(model => model.Patronymic)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.ContactEmail)<b>:</b>
            @Html.DisplayFor(model => model.ContactEmail)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.PhoneNumber)<b>:</b>
            @Html.DisplayFor(model => model.PhoneNumber)
        </div>

    </fieldset>

    <form action=@Url.Action("Edit", "User")>
        <div class="btn-group right" role="group">
            <input type="submit" class="btn btn-primary" value="Редактировать">
        </div>
    </form>

</div>

Eventor_Project/Eventor_Project/Views/User/Edit.cshtml
@model Eventor_Project.Models.User.User
@{
    ViewBag.Title = "Информация о пользователе";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.Password)
        <fieldset>
                <b>@Html.LabelFor(model => model.Nickname)</b>:
                <div data-toggle="tooltip" data-placement="right">
                    @Html.TextBoxFor(x => x.Nickname, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.Nickname)
                </div> <br/>
            <div align="center">
                <img src="~/images/avatar-default.jpg" class="img-rounded" alt="Sample Image">
            </div>

            <div class="row text-center">
                <div class="col-sm-6 contacts">
                    <h2>Контактные данные:</h2>

                    <b>@Html.LabelFor(model => model.PhoneNumber)</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.PhoneNumber, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.PhoneNumber)
                    </div> <br/>

                    <b>Публичный E-mail</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.ContactEmail, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.ContactEmail)
                    </div> <br/>

                    <b>@Html.LabelFor(model => model.Email)</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.Email, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Email)
                    </div> <br/>

                    <div class="btn-group right" role="group">
                        <input type="submit" class="btn btn-success" value="Сохранить">
                    </div>

                    @*<form action=@Url.Action("NewMessage", "Mail") method="POST">
                    @Html.Hidden("recId", Model.UserId)
                    <div class="btn-group right" role="group">
                        <input type="submit" class="btn btn-primary" value="Новое сообщение">
                    </div>
                </form>*@
                </div>

                <div class="col-sm-6 contacts">
                    <h2>Информация о пользователе:</h2>

                    <b>@Html.LabelFor(model => model.Surname)</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.Surname, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Surname)
                    </div> <br/>

                    <b>@Html.LabelFor(model => model.Name)</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.Name, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Name)
                    </div> <br/>

                    <b>@Html.LabelFor(model => model.Patronymic)</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.Patronymic, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Patronymic)
                    </div> <br/>

                    <b>@Html.LabelFor(model => model.PlaceOfLiving)</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.PlaceOfLiving.PlaceInfo, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.PlaceOfLiving.PlaceInfo)
                    </div> <br/>

                    <b>@Html.LabelFor(model => model.PlaceOfStudy)</b>:
                    <div data-toggle="tooltip" data-placement="right">
                        @Html.TextBoxFor(x => x.PlaceOfStudy.PlaceInfo, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.PlaceOfStudy.PlaceInfo)
                    </div> <br/>


                    <b>@Html.LabelFor(model => model.Birthdate)</b>:
                    <div data-toggle="tooltip" data-placement="right" title="Дата рождения">
                        @Html.TextBoxFor(x => x.Birthdate, new {@class = "datepicker-all"})
                        @Html.ValidationMessageFor(x => x.Birthdate)
                    </div> <br/>
                </div>

                <h2> О себе:</h2>
                <div data-toggle="tooltip" data-placement="right">
                    @Html.TextAreaFor(x => x.About, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.About)
                </div> <br/>
            </div>

        </fieldset>
    </div>
}

Eventor_Project/Eventor_Project/Views/User/Hidden.cshtml
@model IEnumerable<Eventor_Project.Models.User.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Register New", "Register")
</p>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nickname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nickname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Patronymic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
        </td>
    </tr>
}

</table>

Eventor_Project/Eventor_Project/Views/User/Index - Копировать.cshtml
@model IEnumerable<Eventor_Project.Models.User.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <p>
        @Html.ActionLink("Register New", "Register")
    </p>

    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nickname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patronymic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nickname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Patronymic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
                    @Html.ActionLink("Info", "Info", new { id = item.UserId })
                    @Html.ActionLink("Delete", "Delete", new { id = item.UserId })

                </td>
            </tr>
        }

    </table>
</div>

Eventor_Project/Eventor_Project/Views/User/Index.cshtml
@using System.Runtime.InteropServices.ComTypes
@model IEnumerable<Eventor_Project.Models.User.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="page-header"><h1>Пользователи</h1></div>
    <div style="margin-bottom: 20px">
        <form action=@Url.Action("Search", "User") role="search">
            <div class="input-group">
                <input type="text" name="title" value="" placeholder="Поиск пользователя" class="form-control" />
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
        @foreach (var item in Model)
        {
            <div class="media">
                <a href=@String.Format("/id/{0}",@item.UserId) class="pull-left">
                    <img src="~/images/avatar-tiny.jpg" class="media-object" alt="Sample Image">
                </a>
                <div class="media-body">
                    <h4 class="media-heading"> <a href=@String.Format("/id/{0}",@item.UserId)> @item.Surname @item.Name  </a><small>  <i>Ник: (@item.Nickname2)</i></small></h4>
                    <p>
                        @if (item.About.Length > 150)
                        {
                            @String.Format("{0}...", item.About.Substring(0, 150))
                        }
                        else
                        {
                            @item.About
                        }
                    </p>
                </div>
            </div>
        }
    </div>
</div>